<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>winexe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>

    <!-- Single File Packaging -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <DebugType>embedded</DebugType>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization> <!-- Removes ~20 MB of international
    culture tables -->
    <DebuggerSupport>false</DebuggerSupport>               <!-- Strips debug hooks -->
    <EventSourceSupport>false</EventSourceSupport>         <!-- Removes EventSource logging -->

    <!-- Optimization & Symbol Settings -->
    <OptimizationPreference>Speed</OptimizationPreference>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon/f1.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Icon/f1.ico" />
    <None Remove="Icon/f1.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon/f1.ico">
      <LogicalName>Icon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Icon/f1.bmp">
      <LogicalName>Icon.bmp</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aether.Physics2D.MG" Version="2.2.0" />
    <PackageReference Include="Apos.Shapes" Version="0.8.1" />
    <PackageReference Include="FontStashSharp.MonoGame" Version="0.8.7" />
    <PackageReference Include="MonoGame.Extended" Version="6.1.0" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*" />
  </ItemGroup>
</Project>